<?php

$labels = array();
$labels['submit'] = 'Abschicken';
$labels['entersecuritycode'] = 'Security Code eingeben';
$labels['reload'] = 'Neu laden';
$labels['back'] = 'Zurück';
$labels['guess'] = "Erraten Sie die Buchstaben und\nZiffern";
$labels['andthen'] = 'und dann';
$labels['followedby'] = 'gefolgt von';
$labels['and'] = 'und';
$labels['andnota'] = 'und nicht ein';
$labels['but'] = 'aber';
$labels['small'] = 'klein';
$labels['letters'] = 'Buchstabe(n)';
$labels['charsbefore'] = 'Buchstabe(n) bevor';

$messages = array();
$messages['captchainput'] = 'Bitte Security Code eingeben';
$messages['captchafailed'] = 'Security Code stimmt nicht überein';

?>