<?php
$labels = array();
$labels['submit'] = 'Submit';
$labels['entersecuritycode'] = 'Enter Security Code';
$labels['reload'] = 'Reload';
$labels['back'] = 'Back';
$labels['guess'] = "Guess the letters and\nnumbers (passphrase riddle)";
$labels['andthen'] = 'and then';
$labels['followedby'] = 'followed by';
$labels['and'] = 'and';
$labels['andnota'] = 'and not a';
$labels['but'] = 'but';
$labels['small'] = 'small';
$labels['letters'] = 'letter(s)';
$labels['charsbefore'] = 'chars before';

$messages = array();
$messages['captchainput'] = 'Please enter Security Code';
$messages['captchafailed'] = 'Security Code does not match';
?>